In [1]:
from datetime import datetime, timedelta
import os
from pathlib import Path
import time

import numpy as np

import pandas as pd


In [3]:
HOME_PATH = Path(os.path.expandvars('$HOME'))
DATA_PATH = HOME_PATH / 'data'
MLTRADE_PATH = DATA_PATH / 'mltrade'
print(DATA_PATH)

/home/misha/data


In [5]:
fpath = MLTRADE_PATH / 'stocks_1.1.18-9.2.24_close.csv'
df = pd.read_csv(fpath, sep=',', header=0, dtype={'Date': np.int64, 'Time': np.int64})
df


Date    Time    Sber   Sberp       Vtb    Gazp     Gmnk     Moex
0       20180103  100000  227.40  191.47  0.047590  131.06  10935.0  2123.68
1       20180103  100500  226.93  190.85  0.047510  130.83  10960.0  2121.75
2       20180103  101000  227.26  190.96  0.047640  131.02  10994.0  2124.32
3       20180103  101500  227.06  191.02  0.047960  130.74  11000.0  2123.57
4       20180103  102000  227.12  191.23  0.047810  130.88  10993.0  2122.94
...          ...     ...     ...     ...       ...     ...      ...      ...
160042  20240209  182000  283.03  283.25  0.024390  163.86  15720.0  3237.46
160043  20240209  182500  282.93  283.19  0.024330  163.81  15714.0  3235.60
160044  20240209  183000  282.91  283.12  0.024325  163.69  15736.0  3234.65
160045  20240209  183500  282.93  283.18  0.024350  163.67  15726.0  3234.73
160046  20240209  184000  282.93  283.18  0.024350  163.67  15726.0  3234.73

[160047 rows x 8 columns]

In [98]:
dates = df['Date'].unique()
for date_ in dates:
    df_day = df[df['Date'] == date_]
    year, month, day = date_ // 10000, (date_ // 100) % 100, date_ % 100
    dt = df_day['Time'].apply(lambda t: int(datetime(year, month, day, t // 10000, (t // 100) % 100, t % 100).timestamp()))
    dt = dt.to_numpy()
    ddt = dt[1:] - dt[:-1]
    if not (ddt == 300).all():
        print(105 - len(dt))


3
10


In [102]:
time.strptime('125417', '%H%M%S') - time.strptime('125318', '%H%M%S')

TypeError: unsupported operand type(s) for -: 'time.struct_time' and 'time.struct_time'

In [106]:
delta = datetime.strptime('125417', '%H%M%S') - datetime.strptime('125218', '%H%M%S')
delta, delta.seconds

(datetime.timedelta(seconds=119), 119)

In [109]:
dt = datetime.strptime('100000', '%H%M%S')
dt, dt + timedelta(minutes=5)

(datetime.datetime(1900, 1, 1, 10, 0), datetime.datetime(1900, 1, 1, 10, 5))

In [114]:
time_pat = '%H%M%S'
time_start = datetime.strptime('100000', time_pat)
time_end = datetime.strptime('184000', time_pat)
delta_5m = timedelta(minutes=5)
time_ = time_start
times = []
while time_ <= time_end:
    times.append(time_)
    time_ += delta_5m
print(len(times))
times_num = [t.hour * 10000 + t.minute * 100 + t.second for t in times]
times_num = np.array(times_num)
times_num

105


array([100000, 100500, 101000, 101500, 102000, 102500, 103000, 103500,
       104000, 104500, 105000, 105500, 110000, 110500, 111000, 111500,
       112000, 112500, 113000, 113500, 114000, 114500, 115000, 115500,
       120000, 120500, 121000, 121500, 122000, 122500, 123000, 123500,
       124000, 124500, 125000, 125500, 130000, 130500, 131000, 131500,
       132000, 132500, 133000, 133500, 134000, 134500, 135000, 135500,
       140000, 140500, 141000, 141500, 142000, 142500, 143000, 143500,
       144000, 144500, 145000, 145500, 150000, 150500, 151000, 151500,
       152000, 152500, 153000, 153500, 154000, 154500, 155000, 155500,
       160000, 160500, 161000, 161500, 162000, 162500, 163000, 163500,
       164000, 164500, 165000, 165500, 170000, 170500, 171000, 171500,
       172000, 172500, 173000, 173500, 174000, 174500, 175000, 175500,
       180000, 180500, 181000, 181500, 182000, 182500, 183000, 183500,
       184000])

In [143]:
def row_to_timestamp(row):
    dt_str = f'{int(row.Date)}{int(row.Time)}'
    dt = datetime.strptime(dt_str, '%Y%m%d%H%M%S')
    return dt.timestamp()

ts = df.apply(row_to_timestamp, axis=1)
df['Timestamp'] = ts - ts[0]
df

Date    Time    Sber   Sberp       Vtb    Gazp     Gmnk     Moex  \
0       20180103  100000  227.40  191.47  0.047590  131.06  10935.0  2123.68   
1       20180103  100500  226.93  190.85  0.047510  130.83  10960.0  2121.75   
2       20180103  101000  227.26  190.96  0.047640  131.02  10994.0  2124.32   
3       20180103  101500  227.06  191.02  0.047960  130.74  11000.0  2123.57   
4       20180103  102000  227.12  191.23  0.047810  130.88  10993.0  2122.94   
...          ...     ...     ...     ...       ...     ...      ...      ...   
160042  20240209  182000  283.03  283.25  0.024390  163.86  15720.0  3237.46   
160043  20240209  182500  282.93  283.19  0.024330  163.81  15714.0  3235.60   
160044  20240209  183000  282.91  283.12  0.024325  163.69  15736.0  3234.65   
160045  20240209  183500  282.93  283.18  0.024350  163.67  15726.0  3234.73   
160046  20240209  184000  282.93  283.18  0.024350  163.67  15726.0  3234.73   

         Timestamp2    Timestamp  
0               0.0          0.0  
1             300.0        300.0  
2             600.0        600.0  
3             900.0        900.0  
4            1200.0       1200.0  
...             ...          ...  
160042  192529200.0  192529200.0  
160043  192529500.0  192529500.0  
160044  192529800.0  192529800.0  
160045  192530100.0  192530100.0  
160046  192530400.0  192530400.0  

[160047 rows x 10 columns]

In [146]:
def row_to_timestamp_2(row):
    date_, time_ = int(row.Date), int(row.Time)
    dt = datetime(
        year=date_ // 10000, month=(date_ // 100) % 100, day=date_ % 100,
        hour=time_ // 10000, minute=(time_ // 100) % 100, second=time_ % 100,
    )
    return dt.timestamp()

ts2 = df.apply(row_to_timestamp_2, axis=1)
df['Timestamp2'] = ts2 - ts2[0]
df

Date    Time    Sber   Sberp       Vtb    Gazp     Gmnk     Moex  \
0       20180103  100000  227.40  191.47  0.047590  131.06  10935.0  2123.68   
1       20180103  100500  226.93  190.85  0.047510  130.83  10960.0  2121.75   
2       20180103  101000  227.26  190.96  0.047640  131.02  10994.0  2124.32   
3       20180103  101500  227.06  191.02  0.047960  130.74  11000.0  2123.57   
4       20180103  102000  227.12  191.23  0.047810  130.88  10993.0  2122.94   
...          ...     ...     ...     ...       ...     ...      ...      ...   
160042  20240209  182000  283.03  283.25  0.024390  163.86  15720.0  3237.46   
160043  20240209  182500  282.93  283.19  0.024330  163.81  15714.0  3235.60   
160044  20240209  183000  282.91  283.12  0.024325  163.69  15736.0  3234.65   
160045  20240209  183500  282.93  283.18  0.024350  163.67  15726.0  3234.73   
160046  20240209  184000  282.93  283.18  0.024350  163.67  15726.0  3234.73   

         Timestamp2    Timestamp  
0               0.0          0.0  
1             300.0        300.0  
2             600.0        600.0  
3             900.0        900.0  
4            1200.0       1200.0  
...             ...          ...  
160042  192529200.0  192529200.0  
160043  192529500.0  192529500.0  
160044  192529800.0  192529800.0  
160045  192530100.0  192530100.0  
160046  192530400.0  192530400.0  

[160047 rows x 10 columns]

In [147]:
(df['Timestamp'] == df['Timestamp2']).all()


True

In [8]:
def calc_yields(df: pd.DataFrame) -> tuple[list[str], list[str]]:
    def calc_yield_for_prices(ps: pd.Series):
        last_price = 0
        for i in range(len(ps)):
            cur_price = ps[i]
            if last_price == 0:
                last_price = cur_price
            if cur_price == 0:
                continue
            y = (cur_price - last_price) / last_price
            ps.iat[i] = y
            last_price = cur_price
    prices_names, yields_names = [], []
    for cn in df.columns:
        if cn in ('Date', 'Time'): continue
        yn = f'{cn}Yield'
        df[yn] = df[cn]
        calc_yield_for_prices(df[yn])
        prices_names.append(cn)
        yields_names.append(yn)
    return prices_names, yields_names

# dfc = df.iloc[:100].copy()
dfc = df.copy()
pnames, ynames = calc_yields(dfc)
dfc

Date    Time    Sber   Sberp       Vtb    Gazp     Gmnk     Moex  \
0       20180103  100000  227.40  191.47  0.047590  131.06  10935.0  2123.68   
1       20180103  100500  226.93  190.85  0.047510  130.83  10960.0  2121.75   
2       20180103  101000  227.26  190.96  0.047640  131.02  10994.0  2124.32   
3       20180103  101500  227.06  191.02  0.047960  130.74  11000.0  2123.57   
4       20180103  102000  227.12  191.23  0.047810  130.88  10993.0  2122.94   
...          ...     ...     ...     ...       ...     ...      ...      ...   
160042  20240209  182000  283.03  283.25  0.024390  163.86  15720.0  3237.46   
160043  20240209  182500  282.93  283.19  0.024330  163.81  15714.0  3235.60   
160044  20240209  183000  282.91  283.12  0.024325  163.69  15736.0  3234.65   
160045  20240209  183500  282.93  283.18  0.024350  163.67  15726.0  3234.73   
160046  20240209  184000  282.93  283.18  0.024350  163.67  15726.0  3234.73   

        SberYield  SberpYield  VtbYield  GazpYield  GmnkYield  MoexYield  
0        0.000000    0.000000  0.000000   0.000000   0.000000   0.000000  
1       -0.002067   -0.003238 -0.001681  -0.001755   0.002286  -0.000909  
2        0.001454    0.000576  0.002736   0.001452   0.003102   0.001211  
3       -0.000880    0.000314  0.006717  -0.002137   0.000546  -0.000353  
4        0.000264    0.001099 -0.003128   0.001071  -0.000636  -0.000297  
...           ...         ...       ...        ...        ...        ...  
160042  -0.000071    0.000000 -0.001637   0.000061  -0.001144  -0.000219  
160043  -0.000353   -0.000212 -0.002460  -0.000305  -0.000382  -0.000575  
160044  -0.000071   -0.000247 -0.000206  -0.000733   0.001400  -0.000294  
160045   0.000071    0.000212  0.001028  -0.000122  -0.000635   0.000025  
160046   0.000000    0.000000  0.000000   0.000000   0.000000   0.000000  

[160047 rows x 14 columns]

In [7]:
pnames, ynames

(['Sber', 'Sberp', 'Vtb', 'Gazp', 'Gmnk', 'Moex'],
 ['SberYield',
  'SberpYield',
  'VtbYield',
  'GazpYield',
  'GmnkYield',
  'MoexYield'])

In [48]:
def calc_yields_2(df: pd.DataFrame) -> tuple[list[str], list[str]]:
    def fill_zeros_with_last(ps: np.ndarray):
        last_price = 0
        for i in range(len(ps)):
            cur_price = ps[i]
            if last_price == 0:
                last_price = cur_price
            if cur_price == 0:
                ps.iat[i] = last_price
    
    prices_names, yields_names = [], []
    for cn in df.columns:
        if cn in ('Date', 'Time'): continue
        yn = f'{cn}Yield'
        assert df[cn][0] > 0
        prices_names.append(cn)
        yields_names.append(yn)
    
    prices = df[prices_names].to_numpy()
    assert (prices[0] > 0).all(), f'Zero prices of the first day:\n{df[prices_names].iloc[0]}'
    for j in range(prices.shape[1]):
        fill_zeros_with_last(prices[:, j])
    yields = (prices[1:] - prices[:-1]) / prices[:-1]

    df = df.iloc[1:].copy()
    for i, yname in enumerate(yields_names):
        df[yname] = np.nan
        col = df[yname]
        for j in range(yields.shape[0]):
            col.iat[j] = yields[j, i]

    return df, prices_names, yields_names

dfc2 = df.iloc[:10].copy()
# dfc2 = df.copy()
dfc2, pnames, ynames = calc_yields_2(dfc2)
dfc2

Date    Time    Sber   Sberp      Vtb    Gazp     Gmnk     Moex  \
1  20180103  100500  226.93  190.85  0.04751  130.83  10960.0  2121.75   
2  20180103  101000  227.26  190.96  0.04764  131.02  10994.0  2124.32   
3  20180103  101500  227.06  191.02  0.04796  130.74  11000.0  2123.57   
4  20180103  102000  227.12  191.23  0.04781  130.88  10993.0  2122.94   
5  20180103  102500  227.00  191.49  0.04783  130.68  10991.0  2123.02   
6  20180103  103000  227.39  191.60  0.04809  131.08  10998.0  2125.75   
7  20180103  103500  228.64  192.38  0.04805  131.39  10999.0  2129.40   
8  20180103  104000  228.69  192.58  0.04800  131.40  11033.0  2131.48   
9  20180103  104500  228.33  192.06  0.04809  131.22  11033.0  2130.88   

   SberYield  SberpYield  VtbYield  GazpYield  GmnkYield  MoexYield  
1  -0.002067   -0.003238 -0.001681  -0.001755   0.002286  -0.000909  
2   0.001454    0.000576  0.002736   0.001452   0.003102   0.001211  
3  -0.000880    0.000314  0.006717  -0.002137   0.000546  -0.000353  
4   0.000264    0.001099 -0.003128   0.001071  -0.000636  -0.000297  
5  -0.000528    0.001360  0.000418  -0.001528  -0.000182   0.000038  
6   0.001718    0.000574  0.005436   0.003061   0.000637   0.001286  
7   0.005497    0.004071 -0.000832   0.002365   0.000091   0.001717  
8   0.000219    0.001040 -0.001041   0.000076   0.003091   0.000977  
9  -0.001574   -0.002700  0.001875  -0.001370   0.000000  -0.000281

In [46]:
(2124.32 - 2121.75) / 2121.75

0.0012112642865559863

In [68]:
def calc_yields_3(df: pd.DataFrame, inplace: bool = True) -> tuple[pd.DataFrame, list[str], list[str]]:
    prices_names, yields_names = [], []
    for cn in df.columns:
        if cn in ('Date', 'Time'): continue
        yn = f'{cn}Yield'
        assert df[cn][0] > 0
        prices_names.append(cn)
        yields_names.append(yn)
    
    prices = df[prices_names].to_numpy()
    assert (prices > 0).all()

    yields = np.ones(prices.shape, prices.dtype)
    yields[1:] = prices[1:] / prices[0]

    if not inplace:
        df = df.copy()
    for i, yname in enumerate(yields_names):
        df[yname] = yields[:, i]

    return df, prices_names, yields_names

dfc3 = df.iloc[:10].copy()
# dfc3 = df.copy()
dfc3, pnames, ynames = calc_yields_3(dfc3)
dfc3

Date    Time    Sber   Sberp      Vtb    Gazp     Gmnk     Moex  \
0  20180103  100000  227.40  191.47  0.04759  131.06  10935.0  2123.68   
1  20180103  100500  226.93  190.85  0.04751  130.83  10960.0  2121.75   
2  20180103  101000  227.26  190.96  0.04764  131.02  10994.0  2124.32   
3  20180103  101500  227.06  191.02  0.04796  130.74  11000.0  2123.57   
4  20180103  102000  227.12  191.23  0.04781  130.88  10993.0  2122.94   
5  20180103  102500  227.00  191.49  0.04783  130.68  10991.0  2123.02   
6  20180103  103000  227.39  191.60  0.04809  131.08  10998.0  2125.75   
7  20180103  103500  228.64  192.38  0.04805  131.39  10999.0  2129.40   
8  20180103  104000  228.69  192.58  0.04800  131.40  11033.0  2131.48   
9  20180103  104500  228.33  192.06  0.04809  131.22  11033.0  2130.88   

   SberYield  SberpYield  VtbYield  GazpYield  GmnkYield  MoexYield  
0   1.000000    1.000000  1.000000   1.000000   1.000000   1.000000  
1   0.997933    0.996762  0.998319   0.998245   1.002286   0.999091  
2   0.999384    0.997336  1.001051   0.999695   1.005396   1.000301  
3   0.998505    0.997650  1.007775   0.997558   1.005944   0.999948  
4   0.998769    0.998747  1.004623   0.998627   1.005304   0.999652  
5   0.998241    1.000104  1.005043   0.997101   1.005121   0.999689  
6   0.999956    1.000679  1.010506   1.000153   1.005761   1.000975  
7   1.005453    1.004753  1.009666   1.002518   1.005853   1.002693  
8   1.005673    1.005797  1.008615   1.002594   1.008962   1.003673  
9   1.004090    1.003081  1.010506   1.001221   1.008962   1.003390

In [60]:
ps = dfc3[[c for c in dfc3.columns if c not in ('Date', 'Time')]].to_numpy()
ys = ps[1:] / ps[:1]
ys

array([[0.99793316, 0.99676189, 0.99831897, 0.99824508, 1.00228624,
        0.9990912 ],
       [0.99938434, 0.9973364 , 1.00105064, 0.9996948 , 1.00539552,
        1.00030136],
       [0.99850484, 0.99764976, 1.00777474, 0.99755837, 1.00594422,
        0.9999482 ],
       [0.99876869, 0.99874654, 1.00462282, 0.99862658, 1.00530407,
        0.99965155],
       [0.99824099, 1.00010446, 1.00504308, 0.99710056, 1.00512117,
        0.99968922],
       [0.99995602, 1.00067896, 1.01050641, 1.0001526 , 1.00576132,
        1.00097472],
       [1.00545295, 1.0047527 , 1.0096659 , 1.00251793, 1.00585277,
        1.00269344],
       [1.00567282, 1.00579725, 1.00861526, 1.00259423, 1.00896205,
        1.00367287],
       [1.00408971, 1.00308142, 1.01050641, 1.00122081, 1.00896205,
        1.00339034]])

In [ ]:
Date,Time,Sber,Sberp,Vtb,Gazp,Gmnk,Moex
20180103,100000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000
20180103,100500,0.99793,0.99676,0.99832,0.99825,1.00229,0.99909
20180103,101000,0.99938,0.99734,1.00105,0.99969,1.00540,1.00030
20180103,101500,0.99850,0.99765,1.00777,0.99756,1.00594,0.99995
20180103,102000,0.99877,0.99875,1.00462,0.99863,1.00530,0.99965
20180103,102500,0.99824,1.00010,1.00504,0.99710,1.00512,0.99969
20180103,103000,0.99996,1.00068,1.01051,1.00015,1.00576,1.00097
20180103,103500,1.00545,1.00475,1.00967,1.00252,1.00585,1.00269
20180103,104000,1.00567,1.00580,1.00862,1.00259,1.00896,1.00367


In [71]:
mask = np.full(10, True, bool)
rng = np.random.default_rng()
inds = rng.choice(len(mask), 5, replace=False)
inds

array([1, 9, 6, 0, 2])

In [72]:
mask[inds] = False
mask

array([False, False, False,  True,  True,  True, False,  True,  True,
       False])

In [87]:
len(df)

160047

In [83]:
mask = np.full(len(ps1), True, bool)
mask[0] = mask[1] = mask[7] = False
ps1[~mask] = 0
ps1

array([[0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00],
       [2.27260e+02, 1.90960e+02, 4.76400e-02, 1.31020e+02, 1.09940e+04,
        2.12432e+03],
       [2.27060e+02, 1.91020e+02, 4.79600e-02, 1.30740e+02, 1.10000e+04,
        2.12357e+03],
       [2.27120e+02, 1.91230e+02, 4.78100e-02, 1.30880e+02, 1.09930e+04,
        2.12294e+03],
       [2.27000e+02, 1.91490e+02, 4.78300e-02, 1.30680e+02, 1.09910e+04,
        2.12302e+03],
       [2.27390e+02, 1.91600e+02, 4.80900e-02, 1.31080e+02, 1.09980e+04,
        2.12575e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00],
       [2.28690e+02, 1.92580e+02, 4.80000e-02, 1.31400e+02, 1.10330e+04,
        2.13148e+03],
       [2.28330e+02, 1.92060e+02, 4.80900e-02, 1.31220e+02, 1.10330e+04,
        2.13088e+03]])

In [85]:
ps1 = ps[:10].copy()
inds = np.array([0, 2, 7])
ps1[inds] = 0
ps1

array([[0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00],
       [2.26930e+02, 1.90850e+02, 4.75100e-02, 1.30830e+02, 1.09600e+04,
        2.12175e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00],
       [2.27060e+02, 1.91020e+02, 4.79600e-02, 1.30740e+02, 1.10000e+04,
        2.12357e+03],
       [2.27120e+02, 1.91230e+02, 4.78100e-02, 1.30880e+02, 1.09930e+04,
        2.12294e+03],
       [2.27000e+02, 1.91490e+02, 4.78300e-02, 1.30680e+02, 1.09910e+04,
        2.12302e+03],
       [2.27390e+02, 1.91600e+02, 4.80900e-02, 1.31080e+02, 1.09980e+04,
        2.12575e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00],
       [2.28690e+02, 1.92580e+02, 4.80000e-02, 1.31400e+02, 1.10330e+04,
        2.13148e+03],
       [2.28330e+02, 1.92060e+02, 4.80900e-02, 1.31220e+02, 1.10330e+04,
        2.13088e+03]])

In [88]:
rng = np.random.default_rng()

In [113]:
n = 20
n_last = 5
n_mid = 4
a = rng.integers(1, 10, size=n)
a

array([8, 2, 1, 1, 3, 8, 2, 3, 8, 9, 8, 4, 3, 8, 6, 9, 5, 4, 1, 2])

In [98]:
inds_last = np.arange(n - n_last, n)
inds_last

array([15, 16, 17, 18, 19])

In [110]:
inds_mid = rng.choice(n - n_last - 1, size=n_mid, replace=False, shuffle=False) + 1
inds_mid

array([8, 3, 2, 4])

In [111]:
inds = np.concatenate([inds_mid, inds_last])
inds

array([ 8,  3,  2,  4, 15, 16, 17, 18, 19])

In [112]:
mask = np.full(n, False)
mask[inds] = True
mask

array([False, False,  True,  True,  True, False, False, False,  True,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [114]:
a[mask] = 0
a

array([8, 2, 0, 0, 0, 8, 2, 3, 0, 9, 8, 4, 3, 8, 6, 0, 0, 0, 0, 0])

In [118]:
b = rng.integers(1, 9, size=(n, 3))
b.T

array([[3, 3, 5, 5, 4, 6, 5, 1, 3, 6, 7, 1, 6, 1, 7, 4, 3, 5, 8, 5],
       [6, 7, 1, 4, 1, 7, 4, 8, 1, 6, 8, 5, 7, 5, 4, 2, 3, 1, 7, 5],
       [1, 5, 1, 8, 5, 5, 5, 7, 5, 2, 6, 7, 4, 3, 4, 2, 5, 5, 5, 2]])

In [119]:
b[mask] = 0
b.T

array([[3, 3, 0, 0, 0, 6, 5, 1, 0, 6, 7, 1, 6, 1, 7, 0, 0, 0, 0, 0],
       [6, 7, 0, 0, 0, 7, 4, 8, 0, 6, 8, 5, 7, 5, 4, 0, 0, 0, 0, 0],
       [1, 5, 0, 0, 0, 5, 5, 7, 0, 2, 6, 7, 4, 3, 4, 0, 0, 0, 0, 0]])

In [156]:
def discount_from_mask(mask: np.ndarray) -> np.ndarray:
    n = len(mask)
    res = np.zeros(n)
    i = 0
    
    def advance(i0: int, ind: int) -> int:
        ind += i0
        if ind >= n or mask[ind]:
            ind += 1
        if ind >= n or mask[ind]:
            ind += 1
        return ind - i0

    while i < n:
        if mask[i]:
            j, up = 0, True
            i_start = i
            k = advance(i_start, 0)
            print(k)
            while i < n and mask[i]:
                if up:
                    j += 1
                    k2 = k // 2
                    if j > k2:
                        j = k2 + k % 2
                        up = False
                    else:
                        k = advance(i_start, k)
                        # print(k)
                else:
                    j -= 1
                res[i] = j
                i += 1
        else:
            i += 1
    return res


In [157]:
print(mask.T)
disc = discount_from_mask(mask)
print(disc.T)

[False False  True  True  True False False False  True False False False
 False False False  True  True  True  True  True]
2
1
2
[0. 0. 1. 2. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 2. 3. 4. 5.]


In [158]:
m = np.array([True, True, True, False, True, True, True, True, False, True, True, True, True, True, False, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True])
print(m)
disc = discount_from_mask(m)
print(disc)

[ True  True  True False  True  True  True  True False  True  True  True
  True  True False  True  True  True  True  True  True  True  True False
  True  True  True  True  True  True  True  True  True  True]
2
2
2
2
2
[ 1.  2.  1.  0.  1.  2.  2.  1.  0.  1.  2.  3.  2.  1.  0.  1.  2.  3.
  4.  4.  3.  2.  1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [6]:
def discount_from_mask2(mask: np.ndarray) -> np.ndarray:
    n = len(mask)
    res = np.zeros(n)
    ind = 0
    while ind < n:
        if mask[ind]:
            ind1 = ind
            while ind1 < n and mask[ind1]:
                res[ind1] = off + 1
                off += 1
        else:
            ind += 1



In [7]:
from dataclasses import dataclass

@dataclass
class FinMetric:
    horizon: int
    diff: float = -1
    diff_mean: float = 0


In [9]:
fm = FinMetric(horizon=1)
l = [fm]
d = {1: fm}

In [10]:
l, d

([FinMetric(horizon=1, diff=-1, diff_mean=0)],
 {1: FinMetric(horizon=1, diff=-1, diff_mean=0)})

In [12]:
fm.diff += 5
fm

FinMetric(horizon=1, diff=9, diff_mean=0)

In [13]:
l, d

([FinMetric(horizon=1, diff=9, diff_mean=0)],
 {1: FinMetric(horizon=1, diff=9, diff_mean=0)})